# Simple workflow for deploying static content to GitHub Pages
name: Deploy documentation to Github Pages

on:
  # Runs on pushes
  push:
    # Targeting the default branch
    branches:
      - "master"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docs
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run docs
      # Needed for JSDoc to generate the correct links
      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # We need to use the current version of the package to avoid caching issues
          path: './docs/@diomeh/concurrent_callback_queue/${{ steps.package-version.outputs.current-version}}/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
